version: "3.8"

services:
  datastore:
    build:
      dockerfile: sdk.Dockerfile
      context: ./docker
    environment:
      - CLOUDSDK_CORE_PROJECT=${GCP_PROJECT:-test}
    ports:
      - "8081"
    volumes:
      - ./docker/data/datastore:/data
    command: [
      "gcloud",
      "beta", 
      "emulators",
      "datastore",
      "start",
      "--host-port=0.0.0.0:8081",
      "--data-dir=/data/db",
    ]
    
  cloud-storage:
    image: fsouza/fake-gcs-server:v1.24.0
    ports:
      - "4443"
    volumes:
      - ./docker/data/cloud_storage:/data
      - ./docker/data/cloud_storage:/storage

  cloud-storage-proxy:
    image: nginx:1.20
    volumes:
      - ./docker/cloud-storage-proxy.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80"
    depends_on:
      - cloud-storage
    links:
      - cloud-storage:cloud-storage-host

  firebase:
    build:
      dockerfile: firebase.Dockerfile
      context: ./docker
    ports:
      - "8001:8001"
      - "8002:8002"
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
      - "9005:9005"
    volumes:
      - ./docker/data/firebase:/data
      - ./docker/firebase.json:/firebase.json
    command: [
      'firebase',
      'emulators:start',
      "--project=${GCP_PROJECT:-test}",
      "--import=/data",
      "--export-on-exit=/data",
    ]
 
  backend:
    build:
      dockerfile: sdk.Dockerfile
      context: ./docker
    environment:
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT:-test}
    depends_on:
      - datastore
      - cloud-storage-proxy
      - firebase
    links:
      - datastore:datastore-host
      - cloud-storage-proxy:cloud-storage-host
      - firebase:firebase-host
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: [
      "dev_appserver.py",
      "app_dev.yaml",
      "--application=${GCP_PROJECT:-test}",
      "--host=0.0.0.0",
      "--port=8080",
      "--admin_host=0.0.0.0",
      "--admin_port=8000",
      "--enable_console",
      "--env_var=DATASTORE_EMULATOR_HOST=datastore-host:8081",
      "--env_var=STORAGE_EMULATOR_HOST=http://cloud-storage-host",
      "--env_var=FIRESTORE_EMULATOR_HOST=firebase-host:9002"
    ] 

