version: "3.8"

services:
  datastore:
    image: google/cloud-sdk:338.0.0
    environment:
      - CLOUDSDK_CORE_PROJECT=${GCP_PROJECT:-test}
    ports:
      - "8081"
    volumes:
      - ./docker/data/datastore:/data
    command: [
      "gcloud",
      "beta", 
      "emulators",
      "datastore",
      "start",
      "--host-port=0.0.0.0:8081",
      "--data-dir=/data/db",
    ]
    networks:
      localnet:
        aliases:
          - "datastore-host"
    
  cloud-storage:
    image: fsouza/fake-gcs-server:v1.24.0
    ports:
      - "4443"
    volumes:
      - ./docker/data/cloud_storage:/data
      - ./docker/data/cloud_storage:/storage
    networks:
      localnet:
        aliases:
          - "cloud-storage-host"
 
  cloud-storage-proxy:
    image: nginx:1.20
    volumes:
      - ./docker/cloud-storage-proxy.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80"
    depends_on:
      - cloud-storage
    links:
      - cloud-storage:cloud-storage-host
    networks:
      localnet:
        aliases:
          - "cloud-storage-proxy-host"
 
  firebase:
    build:
      dockerfile: firebase.Dockerfile
      context: ./docker
    ports:
      - "8001:8001"
      - "8002:8002"
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
      - "9005:9005"
    volumes:
      - ./docker/data/firebase:/data
      - ./docker/firebase.json:/firebase.json
    command: [
      'firebase',
      'emulators:start',
      "--project=${GCP_PROJECT:-test}",
      "--import=/data",
      "--export-on-exit=/data",
    ]
    networks:
      localnet:
        aliases:
          - "firebase-host"
 
  cloud-tasks:
    image: ghcr.io/aertje/cloud-tasks-emulator:1.0.2
    ports:
      - "8123"
    environment:
      - APP_ENGINE_EMULATOR_HOST=http://backend-host:8080
    command: [
      "-host=0.0.0.0",
      "-port=8123",
      "-queue=projects/${GCP_PROJECT:-test}/locations/us-central1/queues/default",
    ]
    networks:
      localnet:
        aliases:
          - "cloud-tasks-host"
 
  backend:
    build:
      dockerfile: docker/backend.Dockerfile
      context: .
    environment:
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT:-test}
      - GAE_SERVICE=default
      - GAE_VERSION=20990101t132058
      - GAE_INSTANCE=fake-instance-id
      - GAE_ENV=localdev
      - GAE_RUNTIME=python37
      - GAE_MEMORY_MB=128
      - DATASTORE_EMULATOR_HOST=datastore-host:8081
      - FIRESTORE_EMULATOR_HOST=firebase-host:9002
      - CLOUD_TASKS_EMULATOR_HOST=cloud-tasks-host:8123
      - STORAGE_EMULATOR_HOST=http://cloud-storage-proxy-host
    depends_on:
      - datastore
      - cloud-storage-proxy
      - firebase
      - cloud-tasks
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./docker/data:/data
    working_dir: /app
    stdin_open: true
    tty: true
    command: ${BACKEND_COMMAND:-uvicorn main:app --port=8080 --host=0.0.0.0 --reload}
    networks:
      localnet:
        aliases:
          - "backend-host"

  gcp-deploy:
    image: google/cloud-sdk:338.0.0
    volumes:
      - ./backend:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: "/bin/bash"

networks:
  localnet:
